#!/bin/bash
#
# This is a wrapper around ansible / ansible-playbook.
#
# Usage ("ansible" mode):
#
#   ./xaasible -m raw all -a 'date'
#
# Usage ("ansible-playbook" mode):
#
#   ./xaasible -l prod
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(cd $(dirname "$0"); /bin/pwd)"

ensure_ansible () {
    if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
        curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
            SUITCASE_DIR=$PWD/ansible-deps-cache \
            SUITCASE_PIP_EXTRA="bcrypt passlib kubernetes pyvmomi ldap3" \
            SUITCASE_ANSIBLE_VERSION=6.3.0 \
            SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
            bash -x
    fi

    . "$PWD"/ansible-deps-cache/lib.sh
    ensure_ansible_runtime
}

ensure_oc () {
    oc --help > /dev/null || fatal <<'PLEASE_INSTALL_OC'

The `oc` command line tool is required. Bailing out.

Please install the `oc` command-line tool on your system, and try
again.

Installation instructions can be found at
https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html


PLEASE_INSTALL_OC
}

ensure_openssl () {
    openssl version > /dev/null || fatal <<'PLEASE_INSTALL_OPENSSL'

The `openssl` command line tool is required. Bailing out.

Please install the `openssl` command-line tool on your system, and try
again.

PLEASE_INSTALL_OPENSSL
}


inventories () {
    echo "-i inventory/openshift-0.yml"
}

###########################################################################

set -e

ensure_ansible
ensure_oc
ensure_openssl
playbook_flags="$(ansible_flag_set_var_homedir xaasible_dir)"

mode=ansible-playbook

while [ "$#" -gt 0 ]; do
  case "$1" in
        kubectl)
            mode="kubectl"
            shift ; break ;;
        -m) mode=ansible
            ansible_args+=("-m")
            shift ;;
        *)
            ansible_args+=("$1")
            shift ;;
    esac
done

case "$mode" in
    ansible-playbook)
        ansible-playbook $playbook_flags $(inventories) "${ansible_args[@]}" \
                         -e @vars/xaasible-vars.yml -e @vars/openshift-vars.yml \
                         playbook.yml
        ;;
    ansible)
        ansible $(inventories) "${ansible_args[@]}"
        ;;
    kubectl)
        kubectl "$@" ;;
esac
