# OpenID-Connect frontend (app-facing) configuration for SATOSA
module: satosa.frontends.openid_connect.OpenIDConnectFrontend
name: OIDC
config:
  provider:
    client_registration_supported: no
    response_types_supported: ["code", "id_token token"]
    subject_types_supported: ["pairwise"]
    scopes_supported:
    - openid
    - email
    - profile
    - tequila
    extra_scopes:
      tequila:
      - groups
    extra_id_token_claims:
      react-starter-kit:
        - profile
  signing_key_path: /saml2-backend-secrets/oidc.key
  client_db_path: /config/clients.json
