- name: Generate '{{ _key }}'
  shell:
    creates: '{{ _key }}'
    cmd: "openssl genrsa 2048 > {{ _key }}"
  tags: satosa.keys

- name: Generate '{{ _cert }}'
  shell:
    creates: '{{ _cert }}'
    cmd: >-
      openssl req -x509 -new -key {{ _key }}
      -batch -subj '/CN={{ _cn }}'
      -days 3650
      -out {{ _cert }}
  tags: satosa.keys
